export const FETCH_CATS = 'FETCH_CATS';
export const TOGGLE_CAT_TO_FAVOURITES = 'TOGGLE_CAT_TO_FAVOURITES';
export const CHANGE_FETCHING_STATUS = 'CHANGE_FETCHING_STATUS';
export const CHANGE_CURRENT_PAGE_NUMBER = 'CHANGE_CURRENT_PAGE_NUMBER';
